### PR TITLE
simple: Fix suggested fixes for S1004

### PR DESCRIPTION
**Pull request by sourya**
Also update go/tools to latest version, as `analysistest.RunWithSuggestedFixes` is
very recent.

Signed-off-by: Sourya Vatsyayan <sourya@deepsource.io>

### CODE REVIEW

**Comment by sourya** [comment]
I have removed the tests for suggested fixes for Windows, because the CR/LF issue was breaking the tests.

The analysistest package's `RunWithSuggestedFixes` does `format.Source(editedFile)`, which removes carriage returns from the edited file (because its doc says that it works like gofmt, and gofmt removes any carriage returns). However, they do not do the same `format.Source` for the `.golden` file used for comparison.

**Comment by dominikh** [comment]
Thanks for the patch, I'll look into it within the next several days.

> However, it does not run format.Source for the .golden file used for comparison. Hence, the carriage returns remain

In that case, wouldn't the golden file already be gofmted by us and not contain any carriage returns in the first place?

**Comment by dominikh** [comment]
Alright, looks like the issue is that git in the CI environment automatically converts files to Windows-style line endings. Once we fix that with a `.gitattributes` file, everything works as expected.

I'll have to read up more on git and line endings. The simplest solution would be to adopt what the Go project does: treat all files as binary, i.e. never change line endings. More complex solutions have rules specific to some file extensions.

**Comment by sourya** [comment]
> In that case, wouldn't the golden file already be gofmted by us and not contain any carriage returns in the first place?

I wasn't able to understand why this was happening.

> Alright, looks like the issue is that git in the CI environment automatically converts files to Windows-style line endings.

Now I know. :)

Thank you for looking into it and fixing it.

**Comment by dominikh** [comment]
Update: I'll merge your PR + my changes on top once https://go-review.googlesource.com/c/tools/+/229257 gets merged.

**Comment by dominikh** [comment]
Never mind, I've merged it ahead of time in a4eb707c4ac4bb176e9241aeb886ea7d135f66a4 – thanks again!

**Pull request closed without merging**
