### PR TITLE
Add promu building config

### PR DESCRIPTION
**Pull request by SuperQ**
* Add Makefile.common from Prometheus project.
* Add minimal Makefile.
* Add VERSION file.
* Add go modules config.
* Add promu configuration.

To build release binaries:
```
make promu
promu crossbuild
promu crossbuild tarballs
promu checksum .tarballs
```

Optionally, publish the release with `github-release`[0].
```
export GITHUB_TOKEN="..."
promu release .tarballs
```

[0]: https://github.com/aktau/github-release

### CODE REVIEW

**Comment by SuperQ** [comment]
@dominikh I was trying to figure out what ldflags change was needed to add the Version info to the binaries. What do you do to build the version into it?

**Comment by dominikh** [comment]
The version is specified in `version/version.go`, `const Version` and is updated on releases. The master branch intentionally doesn't have a version.

Also, and I don't want to be too blunt about this, but I fear you may be wasting your time on this PR :/ Staticcheck doesn't have a complex build process, nor C dependencies. We have a very basic build script in `dist/build.sh`, and I don't really want to pull in a more complex tool for what's essentially two for loops.

**Comment by SuperQ** [comment]
Up to you, I thought I would offer our build tool to improve on your build output. We like using your tools in our codebase so I thought I would contribute something back. Our build tool also easy to integrate with CI. Our release process basically involves pushing a branch + tag to github and the whole thing builds and uploads itself.

If you don't want it, I don't care, it wasn't much effort on my part. It was mostly copy-n-paste from our repo. :smile: Feel free to close this.

FYI, If you changed the `const` to a `var`, you could more easily inject version information at build time.

**Comment by dominikh** [comment]
> Up to you, I thought I would offer our build tool to improve on your build output

If there's anything about the _build output_ that needs improving I'd be excited to hear about it. I am, however, happy with the _build process_.

> If you don't want it, I don't care, it wasn't much effort on my part. It was mostly copy-n-paste from our repo. smile Feel free to close this.

Thank you regardless :)

> FYI, If you changed the const to a var, you could more easily inject version information at build time.

I could, but at the moment there is no need to externally inject it. People can check out a specific version and just `go build` it, no additional build system needed :)

**Pull request closed without merging**
