### PR TITLE
SA5001: clarify message

### LINKED ISSUE #1489: confusing error message with SA5001
```go
	r, err := gzip.NewReader(file)
	defer r.Close() // this outputs file.go:123:2: should check returned error before deferring r.Close() (SA5001)
	if err != nil {
		log.Fatalf("error: %s", err)
	}

```

the error message is a little confusing because it looked to me like it was saying that I needed to check the error from `defer r.Close()` rather than what it actually meant which is that I needed to check the error from `gzip.NewReader` before attempting to close

staticcheck version: `staticcheck 2023.1.6 (v0.4.6)`
staticcheck debug version: 
```
staticcheck 2023.1.6 (v0.4.6)

Compiled with Go version: go1.21.5
Main module:
	honnef.co/go/tools
Dependencies:
	github.com/BurntSushi/toml@v1.2.1
	golang.org/x/exp/typeparams@v0.0.0-20221208152030-732eee02a75a
	golang.org/x/mod@v0.12.0
	golang.org/x/sys@v0.11.0
	golang.org/x/tools@v0.12.1-0.20230825192346-2191a27a6dc5

```

go version: `go version go1.21.0 linux/amd64`

### PR DESCRIPTION
**Pull request by arp242**
Clarify the message by putting the function name in there.

Fixes #1489

### CODE REVIEW

**Comment by dominikh** [comment]
@arp242 FYI, I plan to merge all of your PRs once I'm done with some refactoring (which is currently blocked on an x/tools CL). Hopefully soon.

**Comment by arp242** [comment]
> @arp242 FYI, I plan to merge all of your PRs once I'm done with some refactoring (which is currently blocked on an x/tools CL). Hopefully soon.

Coolio, no hurries. I figured something along these lines. Most PRs aren't too large or complex, and don't mind solving any merge conflicts later on (if need be). And if it gets merged next month or whatever then that's fine with me.

I know it's a bit much, but I got some spare time at the moment and I've been planing to fix some of these issues for years, so it's a bit of a "do it now" or "do it never", so "do it now" seems better. But let me know if there's anything you *don't* want me to do and that's fine.

**Comment by ccoVeille** [comment]
For this PR and others created by @arp242 I'm confused by the PR status.

It's marked as closed, but the PR wasn't merged. So it's like the code was simply ignored is there something I'm missing?

I feel like the PR number was used in another PR to say "close other PR" while we usually close only issues.

**Comment by ccoVeille** [comment]
I mean it appears to everyone they have been discarded while they were merged

**Comment by dominikh** [comment]
The PRs were applied by downloading them as patches, applying them, and making minor modifications to the commits as needed. I use https://github.com/leahneukirchen/git-merge-pr for this process. The created commits contain `Closes:` commands to close the respective PRs. That GitHub cannot differentiate between closing a PR because it was applied in a different way than pushing commits that match the SHAs from the PR and closing a PR because it has been rejected is a fault of GitHub.

**Comment by ccoVeille** [comment]
I don't want to appear as the boring guy, but I think I don't get what happened

**Comment by dominikh** [comment]
This PR was applied as, and closed by, d39a04f5c28ab48494da674d3a4cba2c714287de.

**Comment by ccoVeille** [comment]
> This PR was applied as, and closed by, d39a04f5c28ab48494da674d3a4cba2c714287de.

Yes, it's a commit pushed to master without a PR (apparently), while the current PR was there and ready to be merged

**Comment by Xe** [comment]
GitHub doesn't have a way to say "this exact patch wasn't merged, but the maintainer downloaded it and merged it themselves after editing it locally", which is halfway between "merged" and "closed". Pull requests only operate on that _exact_ patch being merged, not a similar patch derived from a PR.

**Comment by ccoVeille** [comment]
Thanks for your reply

I missed this one, I'm only seeing now
 https://github.com/dominikh/go-tools/pull/1554#issuecomment-2143510308

For me, it's an uncommon workflow, and somehow invalid one. But OK, it's clearer.

**Pull request closed without merging**
