### PR TITLE
analysis/facts: fix `fact_deprecated` analyzer

### PR DESCRIPTION
**Pull request by shmsr**
`fact_deprecated` analyzer is now able to correctly detect all the deprecated const and type. I have also updated `SA1019`'s testdata in order to show the effect on SA1019 after fixing the `fact_deprecated`.

Fixes https://github.com/dominikh/go-tools/issues/1313

Also, it doesn't detect inline comments in some cases, fixed that as well.

Signed-off-by: subham sarkar <sarkar.subhams2@gmail.com>

### CODE REVIEW

**Comment by shmsr** [comment]
cc: @dominikh

**Comment by dominikh** [comment]
Thanks. I'll look at this eventually, but am a bit busy at the moment.

**Comment by shmsr** [comment]
@dominikh ping

**Comment by shmsr** [comment]
Also, found a couple of more bugs with this code. Should I push them to this PR itself?

**Comment by dominikh** [comment]
> Also, found a couple of more bugs with this code. Should I push them to this PR itself?

Yes please.

**Comment by shmsr** [comment]
> > Also, found a couple of more bugs with this code. Should I push them to this PR itself?
> 
> Yes please.

@dominikh Give it a look. I've fixed one more issue with the `deprecated` analyzer.

**Comment by shmsr** [comment]
> > > Also, found a couple of more bugs with this code. Should I push them to this PR itself?
> > 
> > 
> > Yes please.
> 
> @dominikh Give it a look. I've fixed one more issue with the `fact_deprecated` analyzer.

ping @dominikh

**Comment by dominikh** [comment]
It's on my radar. I'll look into it eventually. Sorry about the delay.

**Comment by dominikh** [comment]
Thanks. I've cherry-picked 2dee2d955f0cdf4cf4da62a12b5008df3c267a7c. I didn't apply a31684beb6154ac223653a53a5ded77e4d06a5f9 because "inline comments" aren't the correct way to mark identifiers as deprecated. https://github.com/golang/go/wiki/Deprecated explicitly states that it should be a paragraph in the documentation comment.

**Comment by shmsr** [comment]
> Thanks. I've cherry-picked [2dee2d9](https://github.com/dominikh/go-tools/commit/2dee2d955f0cdf4cf4da62a12b5008df3c267a7c). I didn't apply [a31684b](https://github.com/dominikh/go-tools/commit/a31684beb6154ac223653a53a5ded77e4d06a5f9) because "inline comments" aren't the correct way to mark identifiers as deprecated. https://github.com/golang/go/wiki/Deprecated explicitly states that it should be a paragraph in the documentation comment.

Thanks @dominikh!

**Pull request closed without merging**
